### ISSUE TITLE
Connection Database not Saving

### ISSUE THREAD

**Issue by ehdrianca** [ibv/LDAP-Admin#6]
Hello,

"Private" in "Connections", are not saved after shutting the program down.  All file-system permissions are correct.

Create a new connection
Close the program
Open the program
Notice the connection is no longer there

Work around:
Export connections to a file and then import after starting the program fresh.

**Comment by ibv** [comment]
Hello,

there is probably a problem in Lazarus (since version 1.7) when working with registers.
Please rename "~/.config/LdapAdmin/reg.xml" to "~/.config/LdapAdmin/reg.xml.backup" and copy  (after unzipping) the enclosed reg.xml file  into the "~/.config/LdapAdmin/" directory and try to fix the new connection item.
[reg.xml.zip](https://github.com/ibv/LDAP-Admin/files/1799408/reg.xml.zip)

**Comment by ibv** [comment]
How to fix
1. Create a new connection
2. Close the program LdapAdmin
3. Open file reg.xml in "~/.config/LdapAdmin/" 
4. Replace "HKEY_CLASSES_ROOT" with "HKEY_CURRENT_USER"
Before:
![ldap-before](https://user-images.githubusercontent.com/2648561/39050815-118980dc-44a7-11e8-8141-3e77ee095345.png)
After:
![ldap-after](https://user-images.githubusercontent.com/2648561/39050819-1665967c-44a7-11e8-8823-8967f567b55d.png)
5. Save reg.xml file
6. Open the program LdapAdmin
